version: '3.8'
services:
  nextjs:
    image: node:alpine
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://prisma:prisma@postgres:5432/vitality?schema=public
    volumes:
      - .:/app
      - ./.env:/app/.env
    networks:
      - vitality-network
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev && npm run dev" # --> Development
    # command: sh -c "npm install && npx prisma generate && npx prisma migrate dev && npm run build && npm start" --> Production
    container_name: vitality_nextjs_container

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - vitality-network
    ports:
      - "80:80"
    depends_on:
      - nextjs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: vitality_nginx_container

  postgres: 
    image: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: vitality
    volumes:
      - vitality_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initpostgres.d/init.sql
    networks:
      - vitality-network
    ports:
      - "5432:5432"
    healthcheck:
       test: ['CMD', 'pg_isready', '-U', 'prisma', '-d', 'vitality']
       interval: 5s
       timeout: 5s
       retries: 5
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    container_name: vitality_postgres_container

networks:
  vitality-network:
    driver: bridge

volumes:
  vitality_postgres_data:

