version: '3.8'

services:
  postgres: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: vitality-venture
    ports:
      - "5432:5432"
    volumes:
      - vv_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
       test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'vitality-venture']
       interval: 5s
       timeout: 5s
       retries: 5
    container_name: vv_postgres_container
volumes:
  vv_pgdata: