name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/vitality?schema=public
      DATABASE_TEST_URL: postgresql://postgres:postgres@127.0.0.1:5433/vitality_test?schema=public
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run unit tests
      run: npm run test
      env:
        CI: true